---
- name: Export the directories editing the file /etc/exports
  lineinfile:
    dest: /etc/exports
    regexp: "^{{ item.path }} "
    line: "{{ item.path }} {{ item.export }}"
    create: true
  notify: restart nfs service
  with_items: "{{ nfs_exports }}"

- name: Include OS specific tasks
  include: "{{ item }}"
  with_first_found:
    - "server-{{ ansible_distribution }}.yaml"
    - "server-{{ ansible_os_family }}.yaml"

- name: Enable and start rpcbind
  service: name=rpcbind state=started enabled=yes

- meta: flush_handlers

- name: Check if NFS server service is started
  service: name={{nfs_service}} state=started
