---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansible-role-nfs
  vars:
    nfs_mode: ["server"]
    nfs_exports:
      - path: "/exports"
        export: >
          "*(fsid=0,rw,async,no_root_squash,no_subtree_check,insecure)"
